theme: jekyll-theme-minimal
exclude: [README.md]
title: A Simple Site
logo: img/jetpacktocat.png
author:
    name: Jelmer Poelstra
    email: jelmerpoelstra@gmail.com
    github: jelmerp
    twitter: JelmerPoelstra


