theme: jekyll-theme-minimal
exclude: [README.md]
title: A Simple Site
description: Jelmer's Github Pages testing site
author:
    name: Jelmer Poelstra
    email: jelmerpoelstra@gmail.com
    github: jelmerp
    twitter: JelmerPoelstra


